import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {Outfit} from 'next/font/google'
import { ClerkProvider, UserProfile } from "@clerk/nextjs";
import { DraftModeProvider } from "next/dist/server/async-storage/draft-mode-provider";
import Provider from "./provider";

export const metadata = {
  title: "Ai Study Material Generator",
  description: "Generated by BDU Student",
};

const outfit=Outfit({subsets: ['latin']});

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={outfit.className}
      >

       <Provider>
         {children}
        </Provider>
      </body>
    </html>
    </ClerkProvider>
  );
}
